version: '3.8'

services:
  openai-proxy:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PORT=8000
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/openai-proxy.log 